apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::577301581974:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1NUWJDHOAECGO
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-01-09T17:36:00Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-01-09T17:36:00Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:mapRoles: {}
    manager: kubectl-edit
    operation: Update
    time: "2021-01-16T16:17:51Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1671025"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 997a8707-2e72-4bae-b164-6ffc8b3c4e3e
